// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mearrseorjzedcvjoofm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lYXJyc2Vvcmp6ZWRjdmpvb2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5MjI5MTEsImV4cCI6MjA5OTQ5ODkxMX0.fKvVjbo0CrAnVBZLGxWvpKGqwOQbif3ecPdhXgRsL9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});